---
- name: Install Kafka
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install necessary dependencies
      apt:
        name:
          - zookeeperd
          - wget
        state: present

    - name: Download Kafka
      shell: |
        wget https://downloads.apache.org/kafka/3.8.0/kafka_2.12-3.8.0.tgz
        tar -xvzf kafka_2.12-3.8.0.tgz
        mv kafka_2.12-3.8.0 /usr/local/kafka
      args:
        chdir: /tmp

    - name: Create Kafka service
      copy:
        dest: /etc/systemd/system/kafka.service
        content: |
          [Unit]
          Description=Apache Kafka Server
          Documentation=http://kafka.apache.org/documentation.html
          Requires=zookeeper.service
          After=zookeeper.service

          [Service]
          User=root
          Group=root
          ExecStart=/usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties
          ExecStop=/usr/local/kafka/bin/kafka-server-stop.sh

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Kafka service
      systemd:
        name: kafka
        enabled: yes
        state: started

