---
- name: Install and Configure Kafka in KRaft Mode
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install necessary dependencies
      apt:
        name:
          - wget
          - tar
        state: present

    - name: Download Kafka
      shell: |
        wget https://downloads.apache.org/kafka/3.8.0/kafka_2.12-3.8.0.tgz
        tar -xvzf kafka_2.12-3.8.0.tgz
        mv kafka_2.12-3.8.0 /usr/local/kafka
      args:
        chdir: /tmp

    - name: Create Kafka configuration for KRaft mode
      copy:
        dest: /usr/local/kafka/config/kraft/server.properties
        content: |
          # Basic Kafka configuration for KRaft mode
          broker.id=0
          listeners=PLAINTEXT://0.0.0.0:9092
          log.dirs=/var/lib/kafka/logs
          num.partitions=1
          default.replication.factor=1
          auto.create.topics.enable=true
          process.roles=broker,controller
          controller.quorum.voters=0@localhost:9093
          inter.broker.listener.name=PLAINTEXT
          log.retention.hours=168
          log.segment.bytes=1073741824
          log.retention.check.interval.ms=300000
          zookeeper.connection.timeout.ms=18000
          log.dirs=/var/lib/kafka/logs

    - name: Create Kafka directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /var/lib/kafka
        - /var/lib/kafka/logs

    - name: Create Kafka service
      copy:
        dest: /etc/systemd/system/kafka.service
        content: |
          [Unit]
          Description=Apache Kafka Server
          Documentation=http://kafka.apache.org/documentation.html
          After=network.target

          [Service]
          User=root
          Group=root
          ExecStart=/usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/kraft/server.properties
          ExecStop=/usr/local/kafka/bin/kafka-server-stop.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Kafka service
      systemd:
        name: kafka
        enabled: yes
        state: started